### ISSUE TITLE
Chapter 6 - Suggested adjustments and corrections

### ISSUE THREAD

**Issue by ErikLindstrom42** [nashville-software-school/Vue-Workshop#3]
- When creating a database in Firebase it wants to know if this is Production or Test Mode which isn't mentioned. Whichever one I used set too tight of rules which caused headaches with no descriptive errors down the line.
- After creating a database there is no "+ Add app" as mentioned in the instructions, but instead there are icons for iOS, Android, and web. 
-  App.js is mentioned when App.vue was probably intended
- In the second code block of  the "Adding Styles" section the meme component props aren't quite right and should read as below. This is shown correctly in the next section, but not here
-       <meme
        class="mx-auto"
        :top="topText"
        :bottom="bottomText"
        :imageURL="imageURL"
        :width="800"
      />

- In the "Loading data when the component mounts" section  a <script> block is included that does not mention importing/exporting meme. It IS mentioned later when working on details, but not here

**Comment by AdamSheaffer** [comment]
@ErikLindstrom42 good finds
